### ISSUE TITLE
Populating with orm Doctrine not working as expected...

### ISSUE THREAD

**Issue by mmf-amarcos** [fzaninotto/Faker#117]
Hi I have a Doctrine Entity like this:

``` yml
...    
name: {type: string, length: 255}
address: {type: string, length: 255}
phone_number: {type: string, length: 255}
company: {type: string, length: 255}
email: {type: string, length: 255}
url: {type: string, length: 255}
...
```

When I try to fake on entry with this code

``` php
...
$em = $this->getEntityManager();           
$generator = \Faker\Factory::create($locale);
$populator = new \Faker\ORM\Doctrine\Populator($generator, $em);
$populator->addEntity($this->getEntityName(), 1);
$results = $populator->execute();
...
```

What I get is something like this:
- name: Aut temporibus nam numquam repudiandae. Placeat quae dolor dolorem dolore placeat rerum. Voluptate praesentium repellendus quaerat illo impedit. (INCORRECT not a $faker->name instance)
- address: Paseo Angela, 860, 70º C, 07278, Luján del Penedès (CORRECT)
- phone_number: +34 944-22-3479 (CORRECT)
- company: Laborum maxime qui sit expedita esse aliquam. Velit quis exercitationem et quas minus. Ut quam ducimus dolorem quia impedit minima qui. Voluptatem ab nemo nam ab. Culpa expedita rerum suscipit aut. Aspernatur delectus qui dolorum est debitis labore. (INCORRECT not a $faker->company instance)
- email: anna.quintana@yahoo.com (CORRECT)
- url: Magni porro totam illum aliquam aut molestias sit maiores. Est reiciendis architecto consequatur laboriosam voluptatum. Sit quo consequatur nemo quaerat ipsum dolor corrupti nihil. (INCORRECT not a $faker->url instance)

I have debug to EntityPopulator fillColumns Method on 
https://github.com/fzaninotto/Faker/blob/master/src/Faker/ORM/Doctrine/EntityPopulator.php
And I suppose something is missing/wrong with this line

``` php
$value = is_callable($format) ? $format($insertedEntities, $obj) : $format;
```

But I really cannot follow up. Any ideas?? Thank you in advance.
